//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYearProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertiser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertiser()
        {
            this.Actions = new HashSet<Action>();
            this.Adveriser_LinkType = new HashSet<Adveriser_LinkType>();
            this.Offers = new HashSet<Offer>();
            this.Products = new HashSet<Product>();
        }
    
        public int AdvertiserID { get; set; }
        public string AccountStatus { get; set; }
        public Nullable<double> SevenDayEpc { get; set; }
        public Nullable<double> ThreeMonthEpc { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string RelationshipStatus { get; set; }
        public string MobileTracking { get; set; }
        public string NetworkRank { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<int> ChildCategoryID { get; set; }
        public string PerformanceIncentive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adveriser_LinkType> Adveriser_LinkType { get; set; }
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
